apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- generated-manifest.yaml
images:
- name: cgr.dev/chainguard/nginx
  newName: cgr.dev/chainguard/nginx
  newTag: 6747c95
- name: nginx
  newName: nginx
  newTag: 5c50587
