name: Render Timoni Manifests

on:
  push:
    branches: ["main"]
    paths:
      - "timoni/**"
      - ".github/workflows/workflow.yaml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
        with:
          version: latest # latest or exact version e.g. 0.13.0
      - name: Run Timoni
        run: timoni version

      - name: Render manifests using Timoni
        run: |
          mkdir -p ./manifests
          timoni build myapp ./timoni \
            --values ./timoni/values.cue \
            --values ./timoni/image-SHA-value.yaml \
            > ./manifests/generated-manifest.yaml

      - name: Commit rendered manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          # If no changes, do nothing
          if git diff --cached --quiet; then
            echo "No manifest changes to commit."
            exit 0
          fi

          git commit -m "chore: render timoni manifests"

      - name: Sync changes
        run: |
          git pull origin main
          git push origin HEAD:main