name: Render Timoni Manifests

on:
  push:
    branches: ["main"]
    paths:
      - "timoni/**"
      - ".github/workflows/workflow.yaml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Timoni
        run: |
          # Download and install brew
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          CI=1
          /bin/bash install.sh
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc

          # Install timoni
          brew install stefanprodan/tap/timoni
          timoni version

      - name: Render manifests using Timoni
        run: |
          timoni build myapp ./timoni \
            --namespace default \
            --values ./timoni/values.cue \
            > ../manifests/myapp.yaml

      - name: Commit rendered manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ../manifests/myapp.yaml

          # If no changes, do nothing
          if git diff --cached --quiet; then
            echo "No manifest changes to commit."
            exit 0
          fi

          git commit -m "chore: render timoni manifests"

      - name: Push changes
        run: |
          git push origin HEAD:main